" Dont act like VI
    set nocompatible
" For Vundle
    filetype off
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()
    Plugin 'VundleVim/Vundle.vim'
    Plugin 'fatih/vim-go'
    call vundle#end()
    filetype plugin indent on

    let g:go_def_mode='gopls'
    let g:go_info_mode='gopls'

" Do things based on file types
    filetype plugin on

" Auto complete
    set wildmode=longest,list,full

" Jedi-Vim
    set runtimepath^=~/.vim/bundle/jedi-vim

" CTRL-P Setup
    set runtimepath^=~/.vim/bundle/ctrlp.vim
    helptags ~/.vim/bundle/ctrlp.vim
    let g:ctrlp_working_path_mode = 'ra'
    let g:ctrlp_user_command = 'find %s -type f'
    let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
    let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
    set wildignore+=*/tmp/*,*.so,*.swp,*.zip

" Colors
    set t_Co=256
    syntax enable
    colorscheme desert

" Text
    set encoding=utf-8
    set antialias
    set hlsearch

" Indent
    set nocindent
    set nosmartindent
    set tabstop=4
    set shiftwidth=4
    set autoindent
    set expandtab

" Other
    set hidden
    set number
    set relativenumber
    set splitbelow splitright

" Delete trailing whitespace
    autocmd BufWritePre * %s/\s\+$//e

" Remaps
" Tab to page through buffers
    nnoremap <Tab> :bnext<CR>
    nnoremap <S-Tab> :bprevious<CR>
" Move around in vim windows more easily
    nnoremap <C-h> <C-w>h
    nnoremap <C-j> <C-w>j
    nnoremap <C-k> <C-w>k
    nnoremap <C-l> <C-w>l
