" Dont act like VI
set nocompatible

filetype plugin on

" CTRL-P Setup
set runtimepath^=~/.vim/bundle/ctrlp.vim
helptags ~/.vim/bundle/ctrlp.vim
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_user_command = 'find %s -type f'
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
set wildignore+=*/tmp/*,*.so,*.swp,*.zip 

syntax enable

colorscheme slate
